window.images = [
  {
    image1:
      "./images/1.webp",
    image2:
      "./images/2.webp",
    image3:
      "./images/3.webp",
  },
  {
    image1:
      "./images/4.webp",
    image2:
      "./images/5.webp",
    image3:
      "./images/6.webp",
  },
  {
    image1:
      "./images/7.webp",
    image2:
      "./images/8.webp",
    image3:
      "./images/9.webp",
  },
  {
    image1:
      "./images/10.webp",
    image2:
      "./images/11.webp",
    image3:
      "./images/12.webp",
  },
  {
    image1:
      "./images/13.webp",
    image2:
      "./images/14.webp",
    image3:
      "./images/15.webp",
  },
  {
    image1:
      "./images/16.webp",
    image2:
      "./images/17.webp",
    image3:
      "./images/18.webp",
  },
  {
    image1:
      "./images/19.webp",
    image2:
      "./images/20.webp",
    image3:
      "./images/21.webp",
  },
  {
    image1:
      "./images/22.webp",
    image2:
      "./images/23.webp",
    image3:
      "./images/24.webp",
  },
  {
    image1:
      "./images/25.webp",
    image2:
      "./images/26.webp",
    image3:
      "./images/27.webp",
  },
  {
    image1:
      "./images/28.webp",
    image2:
      "./images/29.webp",
    image3:
      "./images/30.webp",
  },
  {
    image1:
      "./images/31.webp",
    image2:
      "./images/32.webp",
    image3:
      "./images/33.webp",
  },
  {
    image1:
      "./images/34.webp",
    image2:
      "./images/35.webp",
    image3:
      "./images/36.webp",
  },
];